CELL 1 — Imports

In [2]:
import pandas as pd
import numpy as np
import talib

CELL 2 — Load CSV Data

In [3]:
DATA_PATH = "../data/btcusdt_5m_2020_2026.csv"

df = pd.read_csv(DATA_PATH)

df.head()

              datetime     open     high      low    close     volume
0  2020-01-01 00:00:00  7195.24  7196.25  7178.64  7179.78  95.509133
1  2020-01-01 00:05:00  7179.76  7191.77  7178.20  7191.07  59.365225
2  2020-01-01 00:10:00  7193.15  7193.53  7180.24  7180.97  48.068510
3  2020-01-01 00:15:00  7180.97  7186.40  7177.35  7178.29  32.192929
4  2020-01-01 00:20:00  7177.71  7182.46  7175.47  7176.96  49.027397

CELL 3 — Convert Datetime

In [4]:
df["datetime"] = pd.to_datetime(df["datetime"])

df.set_index("datetime", inplace=True)

df.head()

                        open     high      low    close     volume
datetime
2020-01-01 00:00:00  7195.24  7196.25  7178.64  7179.78  95.509133
2020-01-01 00:05:00  7179.76  7191.77  7178.20  7191.07  59.365225
2020-01-01 00:10:00  7193.15  7193.53  7180.24  7180.97  48.068510
2020-01-01 00:15:00  7180.97  7186.40  7177.35  7178.29  32.192929
2020-01-01 00:20:00  7177.71  7182.46  7175.47  7176.96  49.027397

CELL 4 — Check Dataset Shape

In [5]:
print(df.shape)

df.tail()

(630831, 5)

                         open      high       low     close    volume
datetime
2025-12-31 23:40:00  87652.46  87686.09  87652.46  87685.31  10.47354
2025-12-31 23:45:00  87685.31  87697.40  87663.92  87690.61  13.07752
2025-12-31 23:50:00  87690.60  87690.61  87641.14  87641.14  13.66626
2025-12-31 23:55:00  87641.15  87655.31  87641.14  87648.22  18.20491
2026-01-01 00:00:00  87648.21  87701.91  87632.74  87701.91  18.44460

CELL 5 — RSI Indicator

RSI = momentum indicator.

In [6]:
df["rsi_14"] = talib.RSI(
    df["close"],
    timeperiod=14
)

df[["close", "rsi_14"]].tail()

                        close     rsi_14
datetime
2025-12-31 23:40:00  87685.31  47.032743
2025-12-31 23:45:00  87690.61  47.737716
2025-12-31 23:50:00  87641.14  42.104639
2025-12-31 23:55:00  87648.22  43.138772
2026-01-01 00:00:00  87701.91  50.377410

CELL 6 — EMA Indicators

In [7]:
df["ema_20"] = talib.EMA(
    df["close"],
    timeperiod=20
)

df["ema_50"] = talib.EMA(
    df["close"],
    timeperiod=50
)

df["ema_200"] = talib.EMA(
    df["close"],
    timeperiod=200
)

df[
    [
        "close",
        "ema_20",
        "ema_50",
        "ema_200"
    ]
].tail()

                        close        ema_20        ema_50       ema_200
datetime
2025-12-31 23:40:00  87685.31  87704.754040  87725.929599  88038.898065
2025-12-31 23:45:00  87690.61  87703.406989  87724.544517  88035.432512
2025-12-31 23:50:00  87641.14  87697.476799  87721.273751  88031.509203
2025-12-31 23:55:00  87648.22  87692.785675  87718.408898  88027.695380
2026-01-01 00:00:00  87701.91  87693.654659  87717.761883  88024.453735

CELL 7 — ATR (Volatility)

ATR = volatility/range indicator.

In [8]:
df["atr_14"] = talib.ATR(
    df["high"],
    df["low"],
    df["close"],
    timeperiod=14
)

df[["close", "atr_14"]].tail()

                        close     atr_14
datetime
2025-12-31 23:40:00  87685.31  50.554393
2025-12-31 23:45:00  87690.61  49.334793
2025-12-31 23:50:00  87641.14  49.344451
2025-12-31 23:55:00  87648.22  46.831990
2026-01-01 00:00:00  87701.91  48.427562

CELL 8 — MACD

In [9]:
macd, macd_signal, macd_hist = talib.MACD(
    df["close"],
    fastperiod=12,
    slowperiod=26,
    signalperiod=9
)

df["macd"] = macd
df["macd_signal"] = macd_signal
df["macd_hist"] = macd_hist

df[
    [
        "macd",
        "macd_signal",
        "macd_hist"
    ]
].tail()

                          macd  macd_signal  macd_hist
datetime
2025-12-31 23:40:00 -16.824199    -6.802540 -10.021659
2025-12-31 23:45:00 -15.644182    -8.570868  -7.073313
2025-12-31 23:50:00 -18.487710   -10.554237  -7.933473
2025-12-31 23:55:00 -19.940073   -12.431404  -7.508669
2026-01-01 00:00:00 -16.567764   -13.258676  -3.309088

CELL 9 — Bollinger Bands

In [10]:
upper, middle, lower = talib.BBANDS(
    df["close"],
    timeperiod=20
)

df["bb_upper"] = upper
df["bb_middle"] = middle
df["bb_lower"] = lower

df[
    [
        "close",
        "bb_upper",
        "bb_lower"
    ]
].tail()

                        close      bb_upper      bb_lower
datetime
2025-12-31 23:40:00  87685.31  87861.300113  87598.471887
2025-12-31 23:45:00  87690.61  87857.156283  87594.776717
2025-12-31 23:50:00  87641.14  87843.923723  87589.300277
2025-12-31 23:55:00  87648.22  87825.977274  87588.726726
2026-01-01 00:00:00  87701.91  87801.216394  87599.357606

CELL 10 — Candle Body & Wick Features

VERY important for price action AI.

In [11]:
df["body_size"] = abs(
    df["close"] - df["open"]
)

df["upper_wick"] = (
    df["high"] - df[["open", "close"]].max(axis=1)
)

df["lower_wick"] = (
    df[["open", "close"]].min(axis=1) - df["low"]
)

df["candle_range"] = (
    df["high"] - df["low"]
)

df[
    [
        "body_size",
        "upper_wick",
        "lower_wick",
        "candle_range"
    ]
].tail()

                     body_size  upper_wick  lower_wick  candle_range
datetime
2025-12-31 23:40:00      32.85        0.78        0.00         33.63
2025-12-31 23:45:00       5.30        6.79       21.39         33.48
2025-12-31 23:50:00      49.46        0.01        0.00         49.47
2025-12-31 23:55:00       7.07        7.09        0.01         14.17
2026-01-01 00:00:00      53.70        0.00       15.47         69.17

CELL 11 — Bullish / Bearish Candle

In [12]:
df["bullish_candle"] = (
    df["close"] > df["open"]
).astype(int)

df["bearish_candle"] = (
    df["close"] < df["open"]
).astype(int)

df[
    [
        "open",
        "close",
        "bullish_candle",
        "bearish_candle"
    ]
].tail()

                         open     close  bullish_candle  bearish_candle
datetime
2025-12-31 23:40:00  87652.46  87685.31               1               0
2025-12-31 23:45:00  87685.31  87690.61               1               0
2025-12-31 23:50:00  87690.60  87641.14               0               1
2025-12-31 23:55:00  87641.15  87648.22               1               0
2026-01-01 00:00:00  87648.21  87701.91               1               0

CELL 12 — Engulfing Pattern

In [13]:
df["engulfing"] = talib.CDLENGULFING(
    df["open"],
    df["high"],
    df["low"],
    df["close"]
)

df[
    [
        "open",
        "high",
        "low",
        "close",
        "engulfing"
    ]
].tail(20)

                         open      high       low     close  engulfing
datetime
2025-12-31 22:25:00  87843.22  87879.04  87843.21  87854.51          0
2025-12-31 22:30:00  87854.50  87854.51  87739.56  87739.56          0
2025-12-31 22:35:00  87739.56  87804.00  87739.55  87783.13          0
2025-12-31 22:40:00  87783.13  87783.14  87691.85  87733.98        -80
2025-12-31 22:45:00  87733.98  87746.48  87703.38  87742.19          0
2025-12-31 22:50:00  87742.20  87776.58  87656.19  87663.24       -100
2025-12-31 22:55:00  87663.25  87736.61  87663.24  87728.29          0
2025-12-31 23:00:00  87728.30  87728.30  87682.84  87682.85          0
2025-12-31 23:05:00  87682.84  87705.35  87656.29  87694.79          0
2025-12-31 23:10:00  87694.78  87698.50  87669.98  87689.75          0
2025-12-31 23:15:00  87689.76  87689.76  87651.88  87651.88          0
2025-12-31 23:20:00  87651.88  87675.48  87619.67  87675.47          0
2025-12-31 23:25:00  87675.47  87698.02  87675.43  87675.44          0
2025-12-31 23:30:00  87675.44  87690.02  87670.99  87671.00          0
2025-12-31 23:35:00  87670.99  87671.00  87650.27  87652.47          0
2025-12-31 23:40:00  87652.46  87686.09  87652.46  87685.31        100
2025-12-31 23:45:00  87685.31  87697.40  87663.92  87690.61          0
2025-12-31 23:50:00  87690.60  87690.61  87641.14  87641.14          0
2025-12-31 23:55:00  87641.15  87655.31  87641.14  87648.22          0
2026-01-01 00:00:00  87648.21  87701.91  87632.74  87701.91          0

CELL 13 — Doji Pattern

In [14]:
df["doji"] = talib.CDLDOJI(
    df["open"],
    df["high"],
    df["low"],
    df["close"]
)

df[
    [
        "open",
        "close",
        "doji"
    ]
].tail(20)

                         open     close  doji
datetime
2025-12-31 22:25:00  87843.22  87854.51     0
2025-12-31 22:30:00  87854.50  87739.56     0
2025-12-31 22:35:00  87739.56  87783.13     0
2025-12-31 22:40:00  87783.13  87733.98     0
2025-12-31 22:45:00  87733.98  87742.19     0
2025-12-31 22:50:00  87742.20  87663.24     0
2025-12-31 22:55:00  87663.25  87728.29     0
2025-12-31 23:00:00  87728.30  87682.85     0
2025-12-31 23:05:00  87682.84  87694.79     0
2025-12-31 23:10:00  87694.78  87689.75   100
2025-12-31 23:15:00  87689.76  87651.88     0
2025-12-31 23:20:00  87651.88  87675.47     0
2025-12-31 23:25:00  87675.47  87675.44   100
2025-12-31 23:30:00  87675.44  87671.00   100
2025-12-31 23:35:00  87670.99  87652.47     0
2025-12-31 23:40:00  87652.46  87685.31     0
2025-12-31 23:45:00  87685.31  87690.61     0
2025-12-31 23:50:00  87690.60  87641.14     0
2025-12-31 23:55:00  87641.15  87648.22     0
2026-01-01 00:00:00  87648.21  87701.91     0

CELL 14 — Hammer Pattern

In [15]:
df["hammer"] = talib.CDLHAMMER(
    df["open"],
    df["high"],
    df["low"],
    df["close"]
)

df[
    [
        "open",
        "close",
        "hammer"
    ]
].tail(20)

                         open     close  hammer
datetime
2025-12-31 22:25:00  87843.22  87854.51       0
2025-12-31 22:30:00  87854.50  87739.56       0
2025-12-31 22:35:00  87739.56  87783.13       0
2025-12-31 22:40:00  87783.13  87733.98       0
2025-12-31 22:45:00  87733.98  87742.19       0
2025-12-31 22:50:00  87742.20  87663.24       0
2025-12-31 22:55:00  87663.25  87728.29       0
2025-12-31 23:00:00  87728.30  87682.85       0
2025-12-31 23:05:00  87682.84  87694.79       0
2025-12-31 23:10:00  87694.78  87689.75       0
2025-12-31 23:15:00  87689.76  87651.88       0
2025-12-31 23:20:00  87651.88  87675.47     100
2025-12-31 23:25:00  87675.47  87675.44       0
2025-12-31 23:30:00  87675.44  87671.00       0
2025-12-31 23:35:00  87670.99  87652.47       0
2025-12-31 23:40:00  87652.46  87685.31       0
2025-12-31 23:45:00  87685.31  87690.61       0
2025-12-31 23:50:00  87690.60  87641.14       0
2025-12-31 23:55:00  87641.15  87648.22       0
2026-01-01 00:00:00  87648.21  87701.91       0

CELL 15 — Trend Detection

Simple EMA trend logic.

In [16]:
df["trend"] = np.where(
    df["ema_20"] > df["ema_50"],
    "bullish",
    "bearish"
)

df[
    [
        "close",
        "ema_20",
        "ema_50",
        "trend"
    ]
].tail()

                        close        ema_20        ema_50    trend
datetime
2025-12-31 23:40:00  87685.31  87704.754040  87725.929599  bearish
2025-12-31 23:45:00  87690.61  87703.406989  87724.544517  bearish
2025-12-31 23:50:00  87641.14  87697.476799  87721.273751  bearish
2025-12-31 23:55:00  87648.22  87692.785675  87718.408898  bearish
2026-01-01 00:00:00  87701.91  87693.654659  87717.761883  bearish

CELL 16 — Support & Resistance Approximation

Rolling highs/lows.

In [17]:
df["resistance"] = (
    df["high"]
    .rolling(50)
    .max()
)

df["support"] = (
    df["low"]
    .rolling(50)
    .min()
)

df[
    [
        "close",
        "support",
        "resistance"
    ]
].tail()

                        close  support  resistance
datetime
2025-12-31 23:40:00  87685.31  87250.0    87879.04
2025-12-31 23:45:00  87690.61  87250.0    87879.04
2025-12-31 23:50:00  87641.14  87250.0    87879.04
2025-12-31 23:55:00  87648.22  87250.0    87879.04
2026-01-01 00:00:00  87701.91  87250.0    87879.04

CELL 17 — Future Target Label

VERY IMPORTANT for AI training.

Predict:

next candle bullish or bearish

In [18]:
df["future_close"] = df["close"].shift(-1)

df["target"] = np.where(
    df["future_close"] > df["close"],
    1,
    0
)

df[
    [
        "close",
        "future_close",
        "target"
    ]
].tail()

                        close  future_close  target
datetime
2025-12-31 23:40:00  87685.31      87690.61       1
2025-12-31 23:45:00  87690.61      87641.14       0
2025-12-31 23:50:00  87641.14      87648.22       1
2025-12-31 23:55:00  87648.22      87701.91       1
2026-01-01 00:00:00  87701.91           NaN       0

CELL 18 — Remove NaN Rows

Indicators create NaN initially.

In [19]:
df.dropna(inplace=True)

print(df.shape)

(630631, 30)

CELL 19 — Save Feature Dataset

In [20]:
SAVE_PATH = "../data/btcusdt_features.parquet"

df.to_parquet(SAVE_PATH)

print("Saved:", SAVE_PATH)

Saved: ../data/btcusdt_features.parquet

CELL 20 — Final Columns Check

In [21]:
df.columns.tolist()

['open',
 'high',
 'low',
 'close',
 'volume',
 'rsi_14',
 'ema_20',
 'ema_50',
 'ema_200',
 'atr_14',
 'macd',
 'macd_signal',
 'macd_hist',
 'bb_upper',
 'bb_middle',
 'bb_lower',
 'body_size',
 'upper_wick',
 'lower_wick',
 'candle_range',
 'bullish_candle',
 'bearish_candle',
 'engulfing',
 'doji',
 'hammer',
 'trend',
 'resistance',
 'support',
 'future_close',
 'target']